// <auto-generated />
namespace eeduca_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class GrupoMensagem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GrupoMensagem));
        
        string IMigrationMetadata.Id
        {
            get { return "202005200109333_GrupoMensagem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
